version: "3.8"
services:
  mongodb:
    image: mongo
    volumes: 
      - data:/data/db
    #environment:
    # MONGO_INIT_ROOT_USERNAME: max
    # MONGO_INIT_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env
  #backend:


volumes:
  data: